Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: django-allauth in c:\users\negis\appdata\roaming\python\python313\site-packages (0.50.0)
Requirement already satisfied: Django>=2.0 in c:\users\negis\appdata\roaming\python\python313\site-packages (from django-allauth) (5.2.1)
Requirement already satisfied: python3-openid>=3.0.8 in c:\users\negis\appdata\roaming\python\python313\site-packages (from django-allauth) (3.2.0)
Requirement already satisfied: requests-oauthlib>=0.3.0 in c:\users\negis\appdata\roaming\python\python313\site-packages (from django-allauth) (2.0.0)
Requirement already satisfied: requests in c:\users\negis\appdata\roaming\python\python313\site-packages (from django-allauth) (2.32.4)
Requirement already satisfied: pyjwt>=1.7 in c:\users\negis\appdata\roaming\python\python313\site-packages (from pyjwt[crypto]>=1.7->django-allauth) (2.9.0)
Requirement already satisfied: asgiref>=3.8.1 in c:\users\negis\appdata\roaming\python\python313\site-packages (from Django>=2.0->django-allauth) (3.8.1)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\negis\appdata\roaming\python\python313\site-packages (from Django>=2.0->django-allauth) (0.5.3)
Requirement already satisfied: tzdata in c:\users\negis\appdata\roaming\python\python313\site-packages (from Django>=2.0->django-allauth) (2025.2)
Requirement already satisfied: cryptography>=3.4.0 in c:\users\negis\appdata\roaming\python\python313\site-packages (from pyjwt[crypto]>=1.7->django-allauth) (45.0.5)
Requirement already satisfied: cffi>=1.14 in c:\users\negis\appdata\roaming\python\python313\site-packages (from cryptography>=3.4.0->pyjwt[crypto]>=1.7->django-allauth) (1.17.1)
Requirement already satisfied: pycparser in c:\users\negis\appdata\roaming\python\python313\site-packages (from cffi>=1.14->cryptography>=3.4.0->pyjwt[crypto]>=1.7->django-allauth) (2.22)
Requirement already satisfied: defusedxml in c:\users\negis\appdata\roaming\python\python313\site-packages (from python3-openid>=3.0.8->django-allauth) (0.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\negis\appdata\roaming\python\python313\site-packages (from requests-oauthlib>=0.3.0->django-allauth) (3.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\negis\appdata\roaming\python\python313\site-packages (from requests->django-allauth) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\negis\appdata\roaming\python\python313\site-packages (from requests->django-allauth) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\negis\appdata\roaming\python\python313\site-packages (from requests->django-allauth) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\negis\appdata\roaming\python\python313\site-packages (from requests->django-allauth) (2025.6.15)
